DROP TABLE IF EXISTS koolid;
CREATE TABLE koolid(
   koolinimi VARCHAR(50),
   vald VARCHAR(50),
   maakond VARCHAR(50),
   opilasi INT
);
INSERT INTO koolid VALUES('Viimsi Keskkool','Viimsi vald','Harju maakond', 1599);
INSERT INTO koolid VALUES('Tartu Kivilinna G?mnaasium','Tartu linn','Tartu maakond', 1439);
INSERT INTO koolid VALUES('Tallinna 21. Kool','Tallinn linn','Harju maakond', 1167);
INSERT INTO koolid VALUES('Keila Kool','Keila linn','Harju maakond', 1133);
INSERT INTO koolid VALUES('Tallinna Linnam?e Vene L?tseum','Tallinn linn','Harju maakond', 1035);
INSERT INTO koolid VALUES('Tartu Tamme G?mnaasium','Tartu linn','Tartu maakond', 1025);
INSERT INTO koolid VALUES('Gustav Adolfi G?mnaasium','Tallinn linn','Harju maakond', 1017);
INSERT INTO koolid VALUES('P?rnu Koidula G?mnaasium','P?rnu linn','P?rnu maakond', 972);
INSERT INTO koolid VALUES('Tallinna Reaalkool','Tallinn linn','Harju maakond', 963);
INSERT INTO koolid VALUES('Narva Humanitaarg?mnaasium','Narva linn','Ida-Viru maakond', 926);
INSERT INTO koolid VALUES('Vanalinna Hariduskolleegium','Tallinn linn','Harju maakond', 917);
INSERT INTO koolid VALUES('Tallinna Humanitaarg?mnaasium','Tallinn linn','Harju maakond', 906);
INSERT INTO koolid VALUES('J?ri G?mnaasium','Rae vald','Harju maakond', 905);
INSERT INTO koolid VALUES('Tabasalu ?hisg?mnaasium','Harku vald','Harju maakond', 903);
INSERT INTO koolid VALUES('Tallinna L??nemere G?mnaasium','Tallinn linn','Harju maakond', 893);
INSERT INTO koolid VALUES('Tallinna Saksa G?mnaasium','Tallinn linn','Harju maakond', 892);
INSERT INTO koolid VALUES('Kadrioru Saksa G?mnaasium','Tallinn linn','Harju maakond', 890);
INSERT INTO koolid VALUES('Kuressaare G?mnaasium','Kuressaare linn','Saare maakond', 886);
INSERT INTO koolid VALUES('Tallinna ?ism?e Vene L?tseum','Tallinn linn','Harju maakond', 885);
INSERT INTO koolid VALUES('Narva P?hklim?e G?mnaasium','Narva linn','Ida-Viru maakond', 873);
INSERT INTO koolid VALUES('Rakvere Reaalg?mnaasium','Rakvere linn','L??ne-Viru maakond', 871);
INSERT INTO koolid VALUES('Saku G?mnaasium','Saku vald','Harju maakond', 870);
INSERT INTO koolid VALUES('Pelgulinna G?mnaasium','Tallinn linn','Harju maakond', 861);
INSERT INTO koolid VALUES('Tallinna Lillek?la G?mnaasium','Tallinn linn','Harju maakond', 858);
INSERT INTO koolid VALUES('Valga P?hikool','Valga linn','Valga maakond', 850);
INSERT INTO koolid VALUES('V?ru Kreutzwaldi G?mnaasium','V?ru linn','V?ru maakond', 845);
INSERT INTO koolid VALUES('Tallinna 32. Keskkool','Tallinn linn','Harju maakond', 842);
INSERT INTO koolid VALUES('Narva Soldino G?mnaasium','Narva linn','Ida-Viru maakond', 833);
INSERT INTO koolid VALUES('Lasnam?e G?mnaasium','Tallinn linn','Harju maakond', 831);
INSERT INTO koolid VALUES('Jakob Westholmi G?mnaasium','Tallinn linn','Harju maakond', 825);
INSERT INTO koolid VALUES('Tallinna ?ism?e G?mnaasium','Tallinn linn','Harju maakond', 825);
INSERT INTO koolid VALUES('Tartu Kommertsg?mnaasium','Tartu linn','Tartu maakond', 822);
INSERT INTO koolid VALUES('Narva Kesklinna G?mnaasium','Narva linn','Ida-Viru maakond', 821);
INSERT INTO koolid VALUES('Saue G?mnaasium','Saue linn','Harju maakond', 812);
INSERT INTO koolid VALUES('Tartu Annelinna G?mnaasium','Tartu linn','Tartu maakond', 812);
INSERT INTO koolid VALUES('Lasnam?e Vene G?mnaasium','Tallinn linn','Harju maakond', 810);
INSERT INTO koolid VALUES('P?rnu ?lej?e G?mnaasium','P?rnu linn','P?rnu maakond', 786);
INSERT INTO koolid VALUES('Miina H?rma G?mnaasium','Tartu linn','Tartu maakond', 784);
INSERT INTO koolid VALUES('Tallinna Arte G?mnaasium','Tallinn linn','Harju maakond', 781);
INSERT INTO koolid VALUES('Pirita Majandusg?mnaasium','Tallinn linn','Harju maakond', 778);
INSERT INTO koolid VALUES('Tallinna Mustam?e Humanitaarg?mnaasium','Tallinn linn','Harju maakond', 776);
INSERT INTO koolid VALUES('Tartu Mart Reiniku Kool','Tartu linn','Tartu maakond', 776);
INSERT INTO koolid VALUES('Tallinna Pae G?mnaasium','Tallinn linn','Harju maakond', 764);
INSERT INTO koolid VALUES('P?rnu ?hisg?mnaasium','P?rnu linn','P?rnu maakond', 760);
INSERT INTO koolid VALUES('Elva G?mnaasium','Elva linn','Tartu maakond', 752);
INSERT INTO koolid VALUES('Tallinna ?hisg?mnaasium','Tallinn linn','Harju maakond', 743);
INSERT INTO koolid VALUES('Tallinna 53. Keskkool','Tallinn linn','Harju maakond', 738);
INSERT INTO koolid VALUES('Rocca al Mare Kool','Tallinn linn','Harju maakond', 730);
INSERT INTO koolid VALUES('Viljandi Jakobsoni Kool','Viljandi linn','Viljandi maakond', 727);
INSERT INTO koolid VALUES('Kohila G?mnaasium','Kohila vald','Rapla maakond', 725);
INSERT INTO koolid VALUES('Rakvere G?mnaasium','Rakvere linn','L??ne-Viru maakond', 722);
INSERT INTO koolid VALUES('Tallinna Tehnikag?mnaasium','Tallinn linn','Harju maakond', 721);
INSERT INTO koolid VALUES('P?lva ?hisg?mnaasium','P?lva linn','P?lva maakond', 716);
INSERT INTO koolid VALUES('Tartu Karlova G?mnaasium','Tartu linn','Tartu maakond', 716);
INSERT INTO koolid VALUES('Narva Kreenholmi G?mnaasium','Narva linn','Ida-Viru maakond', 712);
INSERT INTO koolid VALUES('Tallinna Prantsuse L?tseum','Tallinn linn','Harju maakond', 709);
INSERT INTO koolid VALUES('?lenurme G?mnaasium','?lenurme vald','Tartu maakond', 697);
INSERT INTO koolid VALUES('Tallinna Rahum?e P?hikool','Tallinn linn','Harju maakond', 690);
INSERT INTO koolid VALUES('P?ltsamaa ?hisg?mnaasium','P?ltsamaa linn','J?geva maakond', 686);
INSERT INTO koolid VALUES('Tallinna T?nism?e Reaalkool','Tallinn linn','Harju maakond', 677);
INSERT INTO koolid VALUES('Saaremaa ?hisg?mnaasium','Kuressaare linn','Saare maakond', 674);
INSERT INTO koolid VALUES('Tartu Descartesi L?tseum','Tartu linn','Tartu maakond', 674);
INSERT INTO koolid VALUES('J?hvi Vene G?mnaasium','J?hvi vald','Ida-Viru maakond', 668);
INSERT INTO koolid VALUES('Tallinna Mahtra G?mnaasium','Tallinn linn','Harju maakond', 668);
INSERT INTO koolid VALUES('Viljandi Kesklinna Kool','Viljandi linn','Viljandi maakond', 667);
INSERT INTO koolid VALUES('Maardu G?mnaasium','Maardu linn','Harju maakond', 665);
INSERT INTO koolid VALUES('Tallinna Inglise Kolled?','Tallinn linn','Harju maakond', 665);
INSERT INTO koolid VALUES('Tallinna Kristiine G?mnaasium','Tallinn linn','Harju maakond', 664);
INSERT INTO koolid VALUES('Kohtla-J?rve Ahtme G?mnaasium','Kohtla-J?rve linn','Ida-Viru maakond', 661);
INSERT INTO koolid VALUES('Tallinna Kesklinna Vene G?mnaasium','Tallinn linn','Harju maakond', 659);
INSERT INTO koolid VALUES('Ehte Humanitaarg?mnaasium','Tallinn linn','Harju maakond', 645);
INSERT INTO koolid VALUES('Tartu Vene L?tseum','Tartu linn','Tartu maakond', 644);
INSERT INTO koolid VALUES('J?hvi G?mnaasium','J?hvi vald','Ida-Viru maakond', 637);
INSERT INTO koolid VALUES('Tallinna Mustam?e Reaalg?mnaasium','Tallinn linn','Harju maakond', 632);
INSERT INTO koolid VALUES('Tallinna Laagna G?mnaasium','Tallinn linn','Harju maakond', 628);
INSERT INTO koolid VALUES('Tallinna N?mme G?mnaasium','Tallinn linn','Harju maakond', 624);
INSERT INTO koolid VALUES('Laagri Kool','Saue vald','Harju maakond', 616);
INSERT INTO koolid VALUES('Tallinna Kuristiku G?mnaasium','Tallinn linn','Harju maakond', 616);
INSERT INTO koolid VALUES('Tallinna Mustj?e G?mnaasium','Tallinn linn','Harju maakond', 604);
INSERT INTO koolid VALUES('Tallinna J?rveotsa G?mnaasium','Tallinn linn','Harju maakond', 600);
INSERT INTO koolid VALUES('Tallinna Mustam?e G?mnaasium','Tallinn linn','Harju maakond', 589);
INSERT INTO koolid VALUES('Tartu Kunstig?mnaasium','Tartu linn','Tartu maakond', 589);
INSERT INTO koolid VALUES('Rapla Vesiroosi G?mnaasium','Rapla vald','Rapla maakond', 581);
INSERT INTO koolid VALUES('M?rjamaa G?mnaasium','M?rjamaa vald','Rapla maakond', 570);
INSERT INTO koolid VALUES('T?ri P?hikool','T?ri vald','J?rva maakond', 569);
INSERT INTO koolid VALUES('Tapa G?mnaasium','Tapa vald','L??ne-Viru maakond', 563);
INSERT INTO koolid VALUES('Paide G?mnaasium','Paide linn','J?rva maakond', 562);
INSERT INTO koolid VALUES('Haapsalu G?mnaasium','Haapsalu linn','L??ne maakond', 559);
INSERT INTO koolid VALUES('J?geva G?mnaasium','J?geva linn','J?geva maakond', 559);
INSERT INTO koolid VALUES('Kadrina Keskkool','Kadrina vald','L??ne-Viru maakond', 556);
INSERT INTO koolid VALUES('Kohtla-J?rve Tammiku G?mnaasium','Kohtla-J?rve linn','Ida-Viru maakond', 550);
INSERT INTO koolid VALUES('Paide ?hisg?mnaasium','Paide linn','J?rva maakond', 549);
INSERT INTO koolid VALUES('Kiili G?mnaasium','Kiili vald','Harju maakond', 547);
INSERT INTO koolid VALUES('P?rnu Vene G?mnaasium','P?rnu linn','P?rnu maakond', 546);
INSERT INTO koolid VALUES('Hugo Treffneri G?mnaasium','Tartu linn','Tartu maakond', 544);
INSERT INTO koolid VALUES('Rapla ?hisg?mnaasium','Rapla vald','Rapla maakond', 541);
INSERT INTO koolid VALUES('Kuusalu Keskkool','Kuusalu vald','Harju maakond', 536);
INSERT INTO koolid VALUES('Kohtla-J?rve Slaavi P?hikool','Kohtla-J?rve linn','Ida-Viru maakond', 525);
INSERT INTO koolid VALUES('Haabersti Vene G?mnaasium','Tallinn linn','Harju maakond', 524);
INSERT INTO koolid VALUES('Tallinna N?mme P?hikool','Tallinn linn','Harju maakond', 522);
INSERT INTO koolid VALUES('Kose G?mnaasium','Kose vald','Harju maakond', 507);
INSERT INTO koolid VALUES('Kohtla-J?rve Kesklinna G?mnaasium','Kohtla-J?rve linn','Ida-Viru maakond', 503);
INSERT INTO koolid VALUES('Narva 6. Kool','Narva linn','Ida-Viru maakond', 502);
INSERT INTO koolid VALUES('Sillam?e Kannuka Kool','Sillam?e linn','Ida-Viru maakond', 501);
INSERT INTO koolid VALUES('Tartu Raatuse G?mnaasium','Tartu linn','Tartu maakond', 500);
INSERT INTO koolid VALUES('Tallinna Kunstig?mnaasium','Tallinn linn','Harju maakond', 498);
INSERT INTO koolid VALUES('Sillam?e Vanalinna Kool','Sillam?e linn','Ida-Viru maakond', 484);
INSERT INTO koolid VALUES('P?rnu Kuninga T?nava P?hikool','P?rnu linn','P?rnu maakond', 481);
INSERT INTO koolid VALUES('P?rnu Vanalinna P?hikool','P?rnu linn','P?rnu maakond', 476);
INSERT INTO koolid VALUES('Kohtla-J?rve ?hisg?mnaasium','Kohtla-J?rve linn','Ida-Viru maakond', 472);
INSERT INTO koolid VALUES('Viljandi G?mnaasium','Viljandi linn','Viljandi maakond', 465);
INSERT INTO koolid VALUES('T?rva G?mnaasium','T?rva linn','Valga maakond', 464);
INSERT INTO koolid VALUES('R?pina ?hisg?mnaasium','R?pina vald','P?lva maakond', 462);
INSERT INTO koolid VALUES('Viljandi Paalalinna Kool','Viljandi linn','Viljandi maakond', 462);
INSERT INTO koolid VALUES('L?hte ?hisg?mnaasium','Tartu vald','Tartu maakond', 446);
INSERT INTO koolid VALUES('Karjamaa G?mnaasium','Tallinn linn','Harju maakond', 445);
INSERT INTO koolid VALUES('Narva Vanalinna Riigikool','Narva linn','Ida-Viru maakond', 438);
INSERT INTO koolid VALUES('Tartu Veeriku Kool','Tartu linn','Tartu maakond', 438);
INSERT INTO koolid VALUES('Kohtla-J?rve J?rve G?mnaasium','Kohtla-J?rve linn','Ida-Viru maakond', 433);
INSERT INTO koolid VALUES('Paikuse P?hikool','Paikuse vald','P?rnu maakond', 431);
INSERT INTO koolid VALUES('K?rdla ?hisg?mnaasium','K?rdla linn','Hiiu maakond', 429);
INSERT INTO koolid VALUES('V?ru Kesklinna G?mnaasium','V?ru linn','V?ru maakond', 428);
INSERT INTO koolid VALUES('Lasnam?e ?ldg?mnaasium','Tallinn linn','Harju maakond', 426);
INSERT INTO koolid VALUES('Kehra G?mnaasium','Anija vald','Harju maakond', 421);
INSERT INTO koolid VALUES('Tartu Kesklinna Kool','Tartu linn','Tartu maakond', 419);
INSERT INTO koolid VALUES('Tallinna Juhkentali G?mnaasium','Tallinn linn','Harju maakond', 417);
INSERT INTO koolid VALUES('Otep?? G?mnaasium','Otep?? vald','Valga maakond', 409);
INSERT INTO koolid VALUES('Tartu Jaan Poska G?mnaasium','Tartu linn','Tartu maakond', 407);
INSERT INTO koolid VALUES('Valga Vene G?mnaasium','Valga linn','Valga maakond', 406);
INSERT INTO koolid VALUES('Tamsalu G?mnaasium','Tamsalu vald','L??ne-Viru maakond', 404);
INSERT INTO koolid VALUES('J?geva ?hisg?mnaasium','J?geva linn','J?geva maakond', 396);
INSERT INTO koolid VALUES('N?o P?hikool','N?o vald','Tartu maakond', 387);
INSERT INTO koolid VALUES('P?rnu R??ma P?hikool','P?rnu linn','P?rnu maakond', 382);
INSERT INTO koolid VALUES('Maardu P?hikool','Maardu linn','Harju maakond', 379);
INSERT INTO koolid VALUES('Kilingi-N?mme G?mnaasium','Saarde vald','P?rnu maakond', 377);
INSERT INTO koolid VALUES('Kuressaare Vanalinna Kool','Kuressaare linn','Saare maakond', 374);
INSERT INTO koolid VALUES('Liivalaia G?mnaasium','Tallinn linn','Harju maakond', 374);
INSERT INTO koolid VALUES('Peetri Lasteaed-P?hikool','Rae vald','Harju maakond', 372);
INSERT INTO koolid VALUES('Tartu Forseliuse G?mnaasium','Tartu linn','Tartu maakond', 371);
INSERT INTO koolid VALUES('Vinni-Pajusti G?mnaasium','Vinni vald','L??ne-Viru maakond', 366);
INSERT INTO koolid VALUES('Tallinna Ranniku G?mnaasium','Tallinn linn','Harju maakond', 362);
INSERT INTO koolid VALUES('Kunda ?hisg?mnaasium','Kunda linn','L??ne-Viru maakond', 358);
INSERT INTO koolid VALUES('Antsla G?mnaasium','Antsla vald','V?ru maakond', 354);
INSERT INTO koolid VALUES('Kalamaja P?hikool','Tallinn linn','Harju maakond', 354);
INSERT INTO koolid VALUES('Tallinna P??sk?la G?mnaasium','Tallinn linn','Harju maakond', 353);
INSERT INTO koolid VALUES('P?rnu S?tevaka Humanitaarg?mnaasium','P?rnu linn','P?rnu maakond', 352);
INSERT INTO koolid VALUES('August Kitzbergi nimeline G?mnaasium','Karksi vald','Viljandi maakond', 350);
INSERT INTO koolid VALUES('Loksa G?mnaasium','Loksa linn','Harju maakond', 350);
INSERT INTO koolid VALUES('Tartu Katoliku Hariduskeskus','Tartu linn','Tartu maakond', 347);
INSERT INTO koolid VALUES('V?ndra G?mnaasium','V?ndra (alev) vald','P?rnu maakond', 346);
INSERT INTO koolid VALUES('P?rnu Hansag?mnaasium','P?rnu linn','P?rnu maakond', 344);
INSERT INTO koolid VALUES('Rakvere Erag?mnaasium','Rakvere linn','L??ne-Viru maakond', 336);
INSERT INTO koolid VALUES('Parksepa Keskkool','V?ru vald','V?ru maakond', 332);
INSERT INTO koolid VALUES('V?ike-Maarja G?mnaasium','V?ike-Maarja vald','L??ne-Viru maakond', 331);
INSERT INTO koolid VALUES('Tartu Hiie Kool','Tartu linn','Tartu maakond', 327);
INSERT INTO koolid VALUES('Kivi?li Vene G?mnaasium','Kivi?li linn','Ida-Viru maakond', 325);
INSERT INTO koolid VALUES('Haapsalu Wiedemanni G?mnaasium','Haapsalu linn','L??ne maakond', 323);
INSERT INTO koolid VALUES('Loo Keskkool','J?el?htme vald','Harju maakond', 312);
INSERT INTO koolid VALUES('Tarvastu G?mnaasium','Tarvastu vald','Viljandi maakond', 312);
INSERT INTO koolid VALUES('Tallinna Juudi Kool','Tallinn linn','Harju maakond', 310);
INSERT INTO koolid VALUES('Kivi?li 1. Keskkool','Kivi?li linn','Ida-Viru maakond', 306);
INSERT INTO koolid VALUES('Tallinna Kivim?e P?hikool','Tallinn linn','Harju maakond', 306);
INSERT INTO koolid VALUES('Tallinna Muusikakeskkool','Tallinn linn','Harju maakond', 299);
INSERT INTO koolid VALUES('Haljala G?mnaasium','Haljala vald','L??ne-Viru maakond', 296);
INSERT INTO koolid VALUES('Sindi G?mnaasium','Sindi linn','P?rnu maakond', 291);
INSERT INTO koolid VALUES('Meriv?lja Kool','Tallinn linn','Harju maakond', 281);
INSERT INTO koolid VALUES('Tallinna Paekaare G?mnaasium','Tallinn linn','Harju maakond', 281);
INSERT INTO koolid VALUES('Koeru Keskkool','Koeru vald','J?rva maakond', 279);
INSERT INTO koolid VALUES('Ristiku P?hikool','Tallinn linn','Harju maakond', 279);
INSERT INTO koolid VALUES('Audentese Erakool','Tallinn linn','Harju maakond', 278);
INSERT INTO koolid VALUES('Lasnam?e P?hikool','Tallinn linn','Harju maakond', 275);
INSERT INTO koolid VALUES('P?lva Keskkool','P?lva linn','P?lva maakond', 274);
INSERT INTO koolid VALUES('Suure-Jaani G?mnaasium','Suure-Jaani vald','Viljandi maakond', 268);
INSERT INTO koolid VALUES('Aruk?la P?hikool','Raasiku vald','Harju maakond', 265);
INSERT INTO koolid VALUES('P?rnu Raek?la Kool','P?rnu linn','P?rnu maakond', 262);
INSERT INTO koolid VALUES('Tallinna Sikupilli Keskkool','Tallinn linn','Harju maakond', 261);
INSERT INTO koolid VALUES('Oskar Lutsu Palamuse G?mnaasium','Palamuse vald','J?geva maakond', 260);
INSERT INTO koolid VALUES('Tartu Herbert Masingu Kool','Tartu linn','Tartu maakond', 253);
INSERT INTO koolid VALUES('Audru Keskkool','Audru vald','P?rnu maakond', 245);
INSERT INTO koolid VALUES('N?o Reaalg?mnaasium','N?o vald','Tartu maakond', 242);
INSERT INTO koolid VALUES('Haapsalu Linna Algkool','Haapsalu linn','L??ne maakond', 241);
INSERT INTO koolid VALUES('Puhja G?mnaasium','Puhja vald','Tartu maakond', 236);
INSERT INTO koolid VALUES('K?ina G?mnaasium','K?ina vald','Hiiu maakond', 234);
INSERT INTO koolid VALUES('Toila G?mnaasium','Toila vald','Ida-Viru maakond', 232);
INSERT INTO koolid VALUES('Kohtla-J?rve J?rve Vene G?mnaasium','Kohtla-J?rve linn','Ida-Viru maakond', 231);
INSERT INTO koolid VALUES('Paldiski Vene G?mnaasium','Paldiski linn','Harju maakond', 230);
INSERT INTO koolid VALUES('Sakala Erag?mnaasium','Tallinn linn','Harju maakond', 230);
INSERT INTO koolid VALUES('Juhan Liivi nim. Alatskivi Keskkool','Alatskivi vald','Tartu maakond', 225);
INSERT INTO koolid VALUES('Vastseliina G?mnaasium','Vastseliina vald','V?ru maakond', 224);
INSERT INTO koolid VALUES('Narva Eesti G?mnaasium','Narva linn','Ida-Viru maakond', 223);
INSERT INTO koolid VALUES('Orissaare G?mnaasium','Orissaare vald','Saare maakond', 218);
INSERT INTO koolid VALUES('Lihula G?mnaasium','Lihula vald','L??ne maakond', 217);
INSERT INTO koolid VALUES('Tallinna Tondi P?hikool','Tallinn linn','Harju maakond', 216);
INSERT INTO koolid VALUES('V?ru 1. P?hikool','V?ru linn','V?ru maakond', 216);
INSERT INTO koolid VALUES('Luunja Keskkool','Luunja vald','Tartu maakond', 215);
INSERT INTO koolid VALUES('Narva Paju Kool','Narva linn','Ida-Viru maakond', 215);
INSERT INTO koolid VALUES('Kallavere Keskkool','Maardu linn','Harju maakond', 213);
INSERT INTO koolid VALUES('R?ngu Keskkool','R?ngu vald','Tartu maakond', 213);
INSERT INTO koolid VALUES('Narva Peetri Kool','Narva linn','Ida-Viru maakond', 212);
INSERT INTO koolid VALUES('Abja G?mnaasium','Abja vald','Viljandi maakond', 211);
INSERT INTO koolid VALUES('Kanepi G?mnaasium','Kanepi vald','P?lva maakond', 204);
INSERT INTO koolid VALUES('J?rva-Jaani G?mnaasium','J?rva-Jaani vald','J?rva maakond', 203);
INSERT INTO koolid VALUES('Tapa Vene G?mnaasium','Tapa vald','L??ne-Viru maakond', 203);
INSERT INTO koolid VALUES('H??demeeste Keskkool','H??demeeste vald','P?rnu maakond', 201);
INSERT INTO koolid VALUES('Rakvere P?hikool','Rakvere linn','L??ne-Viru maakond', 199);
INSERT INTO koolid VALUES('Tartu Waldorfg?mnaasium','Tartu linn','Tartu maakond', 198);
INSERT INTO koolid VALUES('Taebla G?mnaasium','Taebla vald','L??ne maakond', 197);
INSERT INTO koolid VALUES('K?rvek?la P?hikool','Tartu vald','Tartu maakond', 196);
INSERT INTO koolid VALUES('P?rnu-Jaagupi G?mnaasium','Halinga vald','P?rnu maakond', 195);
INSERT INTO koolid VALUES('Avinurme G?mnaasium','Avinurme vald','Ida-Viru maakond', 189);
INSERT INTO koolid VALUES('P??nsi Kool','Viimsi vald','Harju maakond', 188);
INSERT INTO koolid VALUES('Tartu Erakool','Tartu linn','Tartu maakond', 187);
INSERT INTO koolid VALUES('V?hma G?mnaasium','V?hma linn','Viljandi maakond', 185);
INSERT INTO koolid VALUES('Keila ?hisg?mnaasium','Keila linn','Harju maakond', 182);
INSERT INTO koolid VALUES('Audentese Spordig?mnaasium','Tallinn linn','Harju maakond', 177);
INSERT INTO koolid VALUES('Leisi Keskkool','Leisi vald','Saare maakond', 175);
INSERT INTO koolid VALUES('Erakool Intellekt','Kohtla-J?rve linn','Ida-Viru maakond', 174);
INSERT INTO koolid VALUES('Kambja P?hikool','Kambja vald','Tartu maakond', 174);
INSERT INTO koolid VALUES('V?nnu Keskkool','V?nnu vald','Tartu maakond', 174);
INSERT INTO koolid VALUES('Puiga P?hikool','V?ru vald','V?ru maakond', 172);
INSERT INTO koolid VALUES('Laulasmaa Kool','Keila vald','Harju maakond', 171);
INSERT INTO koolid VALUES('T?stamaa Keskkool','T?stamaa vald','P?rnu maakond', 166);
INSERT INTO koolid VALUES('R?uge P?hikool','R?uge vald','V?ru maakond', 165);
INSERT INTO koolid VALUES('Ilmatsalu P?hikool','T?htvere vald','Tartu maakond', 164);
INSERT INTO koolid VALUES('Tori P?hikool','Tori vald','P?rnu maakond', 164);
INSERT INTO koolid VALUES('Kurtna Kool','Saku vald','Harju maakond', 163);
INSERT INTO koolid VALUES('S?meru P?hikool','S?meru vald','L??ne-Viru maakond', 161);
INSERT INTO koolid VALUES('Noarootsi G?mnaasium','Noarootsi vald','L??ne maakond', 160);
INSERT INTO koolid VALUES('Paldiski G?mnaasium','Paldiski linn','Harju maakond', 160);
INSERT INTO koolid VALUES('Sillam?e G?mnaasium','Sillam?e linn','Ida-Viru maakond', 159);
INSERT INTO koolid VALUES('Mammaste Lasteaed-Algkool','P?lva vald','P?lva maakond', 158);
INSERT INTO koolid VALUES('T?ri ?hisg?mnaasium','T?ri vald','J?rva maakond', 158);
INSERT INTO koolid VALUES('Tallinna 37. Keskkool','Tallinn linn','Harju maakond', 156);
INSERT INTO koolid VALUES('Turba G?mnaasium','Nissi vald','Harju maakond', 155);
INSERT INTO koolid VALUES('Aravete Keskkool','Ambla vald','J?rva maakond', 154);
INSERT INTO koolid VALUES('Rannu Keskkool','Rannu vald','Tartu maakond', 153);
INSERT INTO koolid VALUES('Valga G?mnaasium','Valga linn','Valga maakond', 153);
INSERT INTO koolid VALUES('Mustvee Vene G?mnaasium','Mustvee linn','J?geva maakond', 152);
INSERT INTO koolid VALUES('Kullamaa Keskkool','Kullamaa vald','L??ne maakond', 151);
INSERT INTO koolid VALUES('Iisaku G?mnaasium','Iisaku vald','Ida-Viru maakond', 150);
INSERT INTO koolid VALUES('Harkuj?rve P?hikool','Harku vald','Harju maakond', 149);
INSERT INTO koolid VALUES('Kehtna P?hikool','Kehtna vald','Rapla maakond', 148);
INSERT INTO koolid VALUES('Narva-J?esuu Keskkool','Narva-J?esuu linn','Ida-Viru maakond', 148);
INSERT INTO koolid VALUES('Tsirguliina Keskkool','T?lliste vald','Valga maakond', 144);
INSERT INTO koolid VALUES('E.Vilde nim. Juuru G?mnaasium','Juuru vald','Rapla maakond', 143);
INSERT INTO koolid VALUES('N?mme Erakool','Tallinn linn','Harju maakond', 138);
INSERT INTO koolid VALUES('K??pa P?hikool','Lasva vald','V?ru maakond', 137);
INSERT INTO koolid VALUES('Raasiku P?hikool','Raasiku vald','Harju maakond', 137);
INSERT INTO koolid VALUES('Vasalemma P?hikool','Vasalemma vald','Harju maakond', 137);
INSERT INTO koolid VALUES('C.R.Jakobsoni nim.Torma P?hikool','Torma vald','J?geva maakond', 134);
INSERT INTO koolid VALUES('Kolga Keskkool','Kuusalu vald','Harju maakond', 134);
INSERT INTO koolid VALUES('Tartu Kroonuaia Kool','Tartu linn','Tartu maakond', 134);
INSERT INTO koolid VALUES('L?ganuse Keskkool','L?ganuse vald','Ida-Viru maakond', 131);
INSERT INTO koolid VALUES('Mustvee G?mnaasium','Mustvee linn','J?geva maakond', 130);
INSERT INTO koolid VALUES('Rakke G?mnaasium','Rakke vald','L??ne-Viru maakond', 130);
INSERT INTO koolid VALUES('Aseri Keskkool','Aseri vald','Ida-Viru maakond', 128);
INSERT INTO koolid VALUES('J?rvakandi G?mnaasium','J?rvakandi vald','Rapla maakond', 128);
INSERT INTO koolid VALUES('??sm?e P?hikool','Saue vald','Harju maakond', 128);
INSERT INTO koolid VALUES('Valtu P?hikool','Kehtna vald','Rapla maakond', 126);
INSERT INTO koolid VALUES('?ism?e Kool','Tallinn linn','Harju maakond', 126);
INSERT INTO koolid VALUES('M?etaguse P?hikool','M?etaguse vald','Ida-Viru maakond', 125);
INSERT INTO koolid VALUES('V?rska G?mnaasium','V?rska vald','P?lva maakond', 125);
INSERT INTO koolid VALUES('Rakvere Linna Algkool','Rakvere linn','L??ne-Viru maakond', 124);
INSERT INTO koolid VALUES('Puurmani G?mnaasium','Puurmani vald','J?geva maakond', 121);
INSERT INTO koolid VALUES('Ruila P?hikool','Kernu vald','Harju maakond', 120);
INSERT INTO koolid VALUES('Salme P?hikool','Salme vald','Saare maakond', 118);
INSERT INTO koolid VALUES('Oru P?hikool','Kose vald','Harju maakond', 117);
INSERT INTO koolid VALUES('Tabivere G?mnaasium','Tabivere vald','J?geva maakond', 117);
INSERT INTO koolid VALUES('Uuem?isa Lasteaed-Algkool','Ridala vald','L??ne maakond', 117);
INSERT INTO koolid VALUES('Haapsalu Sanatoorne Internaatkool','Haapsalu linn','L??ne maakond', 116);
INSERT INTO koolid VALUES('Heimtali P?hikool','P?rsti vald','Viljandi maakond', 116);
INSERT INTO koolid VALUES('Nissi P?hikool','Nissi vald','Harju maakond', 114);
INSERT INTO koolid VALUES('Puka Keskkool','Puka vald','Valga maakond', 113);
INSERT INTO koolid VALUES('V??tsa P?hikool','V??tsa vald','J?rva maakond', 113);
INSERT INTO koolid VALUES('Keeni P?hikool','Sangaste vald','Valga maakond', 112);
INSERT INTO koolid VALUES('Vaida P?hikool','Rae vald','Harju maakond', 111);
INSERT INTO koolid VALUES('K?rla P?hikool','K?rla vald','Saare maakond', 110);
INSERT INTO koolid VALUES('Mooste P?hikool','Mooste vald','P?lva maakond', 110);
INSERT INTO koolid VALUES('Osula P?hikool','S?merpalu vald','V?ru maakond', 108);
INSERT INTO koolid VALUES('Vara P?hikool','Vara vald','Tartu maakond', 107);
INSERT INTO koolid VALUES('Kuldre Kool','Urvaste vald','V?ru maakond', 106);
INSERT INTO koolid VALUES('Lagedi P?hikool','Rae vald','Harju maakond', 105);
INSERT INTO koolid VALUES('Uulu P?hikool','Tahkuranna vald','P?rnu maakond', 104);
INSERT INTO koolid VALUES('Varstu Keskkool','Varstu vald','V?ru maakond', 104);
INSERT INTO koolid VALUES('J??pre Kool','Audru vald','P?rnu maakond', 103);
INSERT INTO koolid VALUES('P?rnu Vabakool','P?rnu linn','P?rnu maakond', 103);
INSERT INTO koolid VALUES('Viluste P?hikool','Veriora vald','P?lva maakond', 103);
INSERT INTO koolid VALUES('Kalmetu P?hikool','Viiratsi vald','Viljandi maakond', 102);
INSERT INTO koolid VALUES('Vasta Kool','Viru-Nigula vald','L??ne-Viru maakond', 102);
INSERT INTO koolid VALUES('Eurog?mnaasium','Tallinn linn','Harju maakond', 101);
INSERT INTO koolid VALUES('Halliste P?hikool','Halliste vald','Viljandi maakond', 101);
INSERT INTO koolid VALUES('Kallaste Keskkool','Kallaste linn','Tartu maakond', 101);
INSERT INTO koolid VALUES('Laupa P?hikool','T?ri vald','J?rva maakond', 101);
INSERT INTO koolid VALUES('Valjala P?hikool','Valjala vald','Saare maakond', 100);
INSERT INTO koolid VALUES('Ridala P?hikool','Ridala vald','L??ne maakond', 99);
INSERT INTO koolid VALUES('Narva ?igeusu Humanitaarkool','Narva linn','Ida-Viru maakond', 98);
INSERT INTO koolid VALUES('Vaek?la Kool','S?meru vald','L??ne-Viru maakond', 98);
INSERT INTO koolid VALUES('Kammeri Kool','Kambja vald','Tartu maakond', 96);
INSERT INTO koolid VALUES('Kostivere Kool','J?el?htme vald','Harju maakond', 96);
INSERT INTO koolid VALUES('Anna Haava nim Pala Kool','Pala vald','J?geva maakond', 94);
INSERT INTO koolid VALUES('Haapsalu Nikolai Kool','Haapsalu linn','L??ne maakond', 94);
INSERT INTO koolid VALUES('P?haj?rve P?hikool','Otep?? vald','Valga maakond', 94);
INSERT INTO koolid VALUES('Vana-Vigala P?hikool','Vigala vald','Rapla maakond', 93);
INSERT INTO koolid VALUES('Adavere P?hikool','P?ltsamaa vald','J?geva maakond', 91);
INSERT INTO koolid VALUES('Tilsi P?hikool','Laheda vald','P?lva maakond', 91);
INSERT INTO koolid VALUES('Ahtme Kool','Kohtla-J?rve linn','Ida-Viru maakond', 90);
INSERT INTO koolid VALUES('Surju P?hikool','Surju vald','P?rnu maakond', 90);
INSERT INTO koolid VALUES('Aste P?hikool','Kaarma vald','Saare maakond', 89);
INSERT INTO koolid VALUES('Oru Kool','Oru vald','L??ne maakond', 89);
INSERT INTO koolid VALUES('Sauga P?hikool','Sauga vald','P?rnu maakond', 89);
INSERT INTO koolid VALUES('Sillam?e Eesti P?hikool','Sillam?e linn','Ida-Viru maakond', 89);
INSERT INTO koolid VALUES('Juurikaru P?hikool','V?ndra vald','P?rnu maakond', 87);
INSERT INTO koolid VALUES('Kohtla P?hikool','Kohtla-N?mme vald','Ida-Viru maakond', 87);
INSERT INTO koolid VALUES('Lustivere P?hikool','P?ltsamaa vald','J?geva maakond', 87);
INSERT INTO koolid VALUES('Vastse-Kuuste Kool','Vastse-Kuuste vald','P?lva maakond', 87);
INSERT INTO koolid VALUES('Aruk?la Vaba Waldorfkool','Raasiku vald','Harju maakond', 86);
INSERT INTO koolid VALUES('Koigi Kool','Koigi vald','J?rva maakond', 86);
INSERT INTO koolid VALUES('Muhu P?hikool','Muhu vald','Saare maakond', 86);
INSERT INTO koolid VALUES('Porkuni kool','Tamsalu vald','L??ne-Viru maakond', 86);
INSERT INTO koolid VALUES('?mari P?hikool','Vasalemma vald','Harju maakond', 85);
INSERT INTO koolid VALUES('Palupera P?hikool','Palupera vald','Valga maakond', 84);
INSERT INTO koolid VALUES('Are P?hikool','Are vald','P?rnu maakond', 82);
INSERT INTO koolid VALUES('Eesti Rahvusvaheline Kool','Tallinn linn','Harju maakond', 82);
INSERT INTO koolid VALUES('Imavere P?hikool','Imavere vald','J?rva maakond', 82);
INSERT INTO koolid VALUES('Kaiu P?hikool','Kaiu vald','Rapla maakond', 82);
INSERT INTO koolid VALUES('Krabi P?hikool','Varstu vald','V?ru maakond', 82);
INSERT INTO koolid VALUES('Raikk?la Kool','Raikk?la vald','Rapla maakond', 82);
INSERT INTO koolid VALUES('Kiigemetsa Kool','J?geva vald','J?geva maakond', 81);
INSERT INTO koolid VALUES('Retla Kool','T?ri vald','J?rva maakond', 81);
INSERT INTO koolid VALUES('V??na M?isakool','Harku vald','Harju maakond', 81);
INSERT INTO koolid VALUES('Alavere P?hikool','Anija vald','Harju maakond', 80);
INSERT INTO koolid VALUES('Emmaste P?hikool','Emmaste vald','Hiiu maakond', 80);
INSERT INTO koolid VALUES('Uhtna P?hikool','S?meru vald','L??ne-Viru maakond', 80);
INSERT INTO koolid VALUES('Voore P?hikool','Saare vald','J?geva maakond', 80);
INSERT INTO koolid VALUES('Saarepeedi Kool','Saarepeedi vald','Viljandi maakond', 79);
INSERT INTO koolid VALUES('Tallinna Vaba Waldorfkool','Tallinn linn','Harju maakond', 79);
INSERT INTO koolid VALUES('Albu P?hikool','Albu vald','J?rva maakond', 78);
INSERT INTO koolid VALUES('Hagudi P?hikool','Rapla vald','Rapla maakond', 78);
INSERT INTO koolid VALUES('Tartu Maarja Kool','Tartu linn','Tartu maakond', 78);
INSERT INTO koolid VALUES('Valga Jaanikese Kool','Valga linn','Valga maakond', 78);
INSERT INTO koolid VALUES('Laekvere P?hikool','Laekvere vald','L??ne-Viru maakond', 77);
INSERT INTO koolid VALUES('Orava P?hikool','Orava vald','P?lva maakond', 76);
INSERT INTO koolid VALUES('Sillaotsa Kool','Haaslava vald','Tartu maakond', 76);
INSERT INTO koolid VALUES('Erakool L?te','Keila linn','Harju maakond', 75);
INSERT INTO koolid VALUES('Friedebert Tuglase nim. Ahja Kool','Ahja vald','P?lva maakond', 75);
INSERT INTO koolid VALUES('Lauka P?hikool','K?rgessaare vald','Hiiu maakond', 75);
INSERT INTO koolid VALUES('P?rnj?e P?hikool','V?ndra vald','P?rnu maakond', 75);
INSERT INTO koolid VALUES('Palivere P?hikool','Taebla vald','L??ne maakond', 74);
INSERT INTO koolid VALUES('?mmuste Kool','Tarvastu vald','Viljandi maakond', 74);
INSERT INTO koolid VALUES('Olustvere P?hikool','Suure-Jaani vald','Viljandi maakond', 73);
INSERT INTO koolid VALUES('Roosna-Alliku P?hikool','Roosna-Alliku vald','J?rva maakond', 73);
INSERT INTO koolid VALUES('Kolga-Jaani P?hikool','Kolga-Jaani vald','Viljandi maakond', 72);
INSERT INTO koolid VALUES('M?niste Kool','M?niste vald','V?ru maakond', 72);
INSERT INTO koolid VALUES('Tallinna Konstantin P?tsi Vaba?hukool','Tallinn linn','Harju maakond', 72);
INSERT INTO koolid VALUES('Haanja Kool','Haanja vald','V?ru maakond', 71);
INSERT INTO koolid VALUES('Hummuli P?hikool','Hummuli vald','Valga maakond', 71);
INSERT INTO koolid VALUES('Tallinna Soome Kool','Tallinn linn','Harju maakond', 71);
INSERT INTO koolid VALUES('Padise P?hikool','Padise vald','Harju maakond', 70);
INSERT INTO koolid VALUES('Risti P?hikool','Risti vald','L??ne maakond', 70);
INSERT INTO koolid VALUES('S?merpalu P?hikool','S?merpalu vald','V?ru maakond', 70);
INSERT INTO koolid VALUES('Ferdinand von Wrangelli nimeline Roela Lasteaed-P?hikool','Vinni vald','L??ne-Viru maakond', 69);
INSERT INTO koolid VALUES('Lasila P?hikool','Rakvere vald','L??ne-Viru maakond', 69);
INSERT INTO koolid VALUES('Ardu Kool','K?ue vald','Harju maakond', 68);
INSERT INTO koolid VALUES('L?llem?e P?hikool','Karula vald','Valga maakond', 68);
INSERT INTO koolid VALUES('Palade P?hikool','P?halepa vald','Hiiu maakond', 68);
INSERT INTO koolid VALUES('Laiuse P?hikool','J?geva vald','J?geva maakond', 67);
INSERT INTO koolid VALUES('Melliste Algkool-Lasteaed','M?ksa vald','Tartu maakond', 67);
INSERT INTO koolid VALUES('Viiratsi Kool','Viiratsi vald','Viljandi maakond', 67);
INSERT INTO koolid VALUES('Kirivere P?hikool','K?o vald','Viljandi maakond', 66);
INSERT INTO koolid VALUES('Simuna Kool','V?ike-Maarja vald','L??ne-Viru maakond', 66);
INSERT INTO koolid VALUES('Tallinna Balletikooli ?ldharidusklassid','Tallinn linn','Harju maakond', 66);
INSERT INTO koolid VALUES('Tallinna Heleni Kool','Tallinn linn','Harju maakond', 66);
INSERT INTO koolid VALUES('Maidla Kool','Maidla vald','Ida-Viru maakond', 65);
INSERT INTO koolid VALUES('Noarootsi Kool','Noarootsi vald','L??ne maakond', 65);
INSERT INTO koolid VALUES('Saverna P?hikool','Valgj?rve vald','P?lva maakond', 65);
INSERT INTO koolid VALUES('EBS G?mnaasium','Tallinn linn','Harju maakond', 64);
INSERT INTO koolid VALUES('Lahmuse Kool','Suure-Jaani vald','Viljandi maakond', 64);
INSERT INTO koolid VALUES('Holstre Kool','Paistu vald','Viljandi maakond', 63);
INSERT INTO koolid VALUES('J.V.Veski nim. Maarja P?hikool','Tabivere vald','J?geva maakond', 63);
INSERT INTO koolid VALUES('Krootuse P?hikool','K?lleste vald','P?lva maakond', 63);
INSERT INTO koolid VALUES('Kernu P?hikool','Kernu vald','Harju maakond', 62);
INSERT INTO koolid VALUES('Kosej?e kool','Kose vald','Harju maakond', 62);
INSERT INTO koolid VALUES('S?rgavere Lasteaed-P?hikool','Suure-Jaani vald','Viljandi maakond', 62);
INSERT INTO koolid VALUES('Virtsu Kool','Hanila vald','L??ne maakond', 62);
INSERT INTO koolid VALUES('Risti P?hikool (Harju)','Padise vald','Harju maakond', 61);
INSERT INTO koolid VALUES('Keila-Joa Sanatoorne Internaatkool','Harku vald','Harju maakond', 60);
INSERT INTO koolid VALUES('Konguta Kool','Konguta vald','Tartu maakond', 60);
INSERT INTO koolid VALUES('Paistu Kool','Paistu vald','Viljandi maakond', 60);
INSERT INTO koolid VALUES('P?lula Kool','R?gavere vald','L??ne-Viru maakond', 60);
INSERT INTO koolid VALUES('Illuka Kool','Illuka vald','Ida-Viru maakond', 58);
INSERT INTO koolid VALUES('V?su Kool','Vihula vald','L??ne-Viru maakond', 58);
INSERT INTO koolid VALUES('Vaimastvere Kool','J?geva vald','J?geva maakond', 57);
INSERT INTO koolid VALUES('Varbla P?hikool','Varbla vald','P?rnu maakond', 57);
INSERT INTO koolid VALUES('Aegviidu Kool','Aegviidu vald','Harju maakond', 56);
INSERT INTO koolid VALUES('Kabala Lasteaed-P?hikool','Raikk?la vald','Rapla maakond', 56);
INSERT INTO koolid VALUES('Kallem?e Kool','Valjala vald','Saare maakond', 56);
INSERT INTO koolid VALUES('Kildu P?hikool','Suure-Jaani vald','Viljandi maakond', 56);
INSERT INTO koolid VALUES('Kiltsi P?hikool','V?ike-Maarja vald','L??ne-Viru maakond', 56);
INSERT INTO koolid VALUES('Siimusti Lasteaed-Algkool','J?geva vald','J?geva maakond', 56);
INSERT INTO koolid VALUES('Sinim?e P?hikool','Vaivara vald','Ida-Viru maakond', 56);
INSERT INTO koolid VALUES('Viljandi Kaare Kool','Viljandi linn','Viljandi maakond', 56);
INSERT INTO koolid VALUES('M?isak?la Kool','M?isak?la linn','Viljandi maakond', 55);
INSERT INTO koolid VALUES('Tallinna Toomkool','Tallinn linn','Harju maakond', 55);
INSERT INTO koolid VALUES('Tartu Emaj?e Kool','Tartu linn','Tartu maakond', 55);
INSERT INTO koolid VALUES('Eidapere Kool','Kehtna vald','Rapla maakond', 54);
INSERT INTO koolid VALUES('K?pu P?hikool','K?pu vald','Viljandi maakond', 54);
INSERT INTO koolid VALUES('L?manda P?hikool','L?manda vald','Saare maakond', 54);
INSERT INTO koolid VALUES('MT? Kool 21. sajandil Haabersti Vene Erag?mnaasium','Tallinn linn','Harju maakond', 54);
INSERT INTO koolid VALUES('P?inurme Internaatkool','Koigi vald','J?rva maakond', 54);
INSERT INTO koolid VALUES('Tornim?e P?hikool','P?ide vald','Saare maakond', 54);
INSERT INTO koolid VALUES('Audentese Spordig?mnaasiumi Otep?? filiaal','Otep?? vald','Valga maakond', 53);
INSERT INTO koolid VALUES('Johannese Kool ja Lasteaed Rosmal','P?lva vald','P?lva maakond', 53);
INSERT INTO koolid VALUES('J?neda Kool','Tapa vald','L??ne-Viru maakond', 53);
INSERT INTO koolid VALUES('Kivi-Vigala P?hikool','Vigala vald','Rapla maakond', 53);
INSERT INTO koolid VALUES('Laeva P?hikool','Laeva vald','Tartu maakond', 53);
INSERT INTO koolid VALUES('Mustjala Lasteaed-P?hikool','Mustjala vald','Saare maakond', 53);
INSERT INTO koolid VALUES('Tallinna Mustam?e 1. Lasteaed-Algkool','Tallinn linn','Harju maakond', 53);
INSERT INTO koolid VALUES('Koonga P?hikool','Koonga vald','P?rnu maakond', 52);
INSERT INTO koolid VALUES('Kose-Uuem?isa Lasteaed-Kool','Kose vald','Harju maakond', 52);
INSERT INTO koolid VALUES('Kodila P?hikool','Rapla vald','Rapla maakond', 50);
INSERT INTO koolid VALUES('Kolkja P?hikool','Peipsi??re vald','Tartu maakond', 50);
INSERT INTO koolid VALUES('Tartu Kristlik P?hikool','Tartu linn','Tartu maakond', 50);
INSERT INTO koolid VALUES('Urvaste Kool','Urvaste vald','V?ru maakond', 50);
INSERT INTO koolid VALUES('Lehtse Kool','Tapa vald','L??ne-Viru maakond', 49);
INSERT INTO koolid VALUES('Leie P?hikool','Kolga-Jaani vald','Viljandi maakond', 49);
INSERT INTO koolid VALUES('Merem?e Kool','Merem?e vald','V?ru maakond', 49);
INSERT INTO koolid VALUES('Valgu P?hikool','M?rjamaa vald','Rapla maakond', 49);
INSERT INTO koolid VALUES('Hargla Kool','Taheva vald','Valga maakond', 48);
INSERT INTO koolid VALUES('Muuga P?hikool','Laekvere vald','L??ne-Viru maakond', 47);
INSERT INTO koolid VALUES('Viljandi Vaba Waldorfkool','Viljandi linn','Viljandi maakond', 47);
INSERT INTO koolid VALUES('Ala P?hikool','Helme vald','Valga maakond', 46);
INSERT INTO koolid VALUES('Kaali Kool','Pihtla vald','Saare maakond', 46);
INSERT INTO koolid VALUES('Kihnu Kool','Kihnu vald','P?rnu maakond', 46);
INSERT INTO koolid VALUES('Metsapoole P?hikool','H??demeeste vald','P?rnu maakond', 46);
INSERT INTO koolid VALUES('T??ksi P?hikool','Suure-Jaani vald','Viljandi maakond', 46);
INSERT INTO koolid VALUES('Kuuste Kool','Kambja vald','Tartu maakond', 45);
INSERT INTO koolid VALUES('Esku-Kamari Kool','P?ltsamaa vald','J?geva maakond', 44);
INSERT INTO koolid VALUES('Martna P?hikool','Martna vald','L??ne maakond', 44);
INSERT INTO koolid VALUES('Peetri Kool','Kareda vald','J?rva maakond', 43);
INSERT INTO koolid VALUES('Tootsi Lasteaed-P?hikool','Tootsi vald','P?rnu maakond', 43);
INSERT INTO koolid VALUES('Lohusuu Kool','Lohusuu vald','Ida-Viru maakond', 42);
INSERT INTO koolid VALUES('Tapa Erikool','Tapa vald','L??ne-Viru maakond', 42);
INSERT INTO koolid VALUES('Kauksi P?hikool','Mooste vald','P?lva maakond', 41);
INSERT INTO koolid VALUES('P?rnu Toimetulekukool','P?rnu linn','P?rnu maakond', 40);
INSERT INTO koolid VALUES('Vihasoo Lasteaed-Algkool','Kuusalu vald','Harju maakond', 40);
INSERT INTO koolid VALUES('Alu Lasteaed-Algkool','Rapla vald','Rapla maakond', 39);
INSERT INTO koolid VALUES('Ambla Lasteaed-P?hikool','Ambla vald','J?rva maakond', 39);
INSERT INTO koolid VALUES('Kihelkonna Kool','Kihelkonna vald','Saare maakond', 38);
INSERT INTO koolid VALUES('Mikitam?e Kool','Mikitam?e vald','P?lva maakond', 37);
INSERT INTO koolid VALUES('Riidaja P?hikool','P?drala vald','Valga maakond', 37);
INSERT INTO koolid VALUES('Tahkuranna Lasteaed-Algkool','Tahkuranna vald','P?rnu maakond', 37);
INSERT INTO koolid VALUES('Vidruka Kool','Taebla vald','L??ne maakond', 37);
INSERT INTO koolid VALUES('K?o P?hikool','Tallinn linn','Harju maakond', 36);
INSERT INTO koolid VALUES('Tallinna Laagna Lasteaed-P?hikool','Tallinn linn','Harju maakond', 36);
INSERT INTO koolid VALUES('Tudulinna P?hikool','Tudulinna vald','Ida-Viru maakond', 36);
INSERT INTO koolid VALUES('"""Edu Valem"" Erakool"','Tallinn linn','Harju maakond', 35);
INSERT INTO koolid VALUES('Kahtla Lasteaed-P?hikool','Laimjala vald','Saare maakond', 35);
INSERT INTO koolid VALUES('K?ru P?hikool','K?ru vald','Rapla maakond', 35);
INSERT INTO koolid VALUES('Lehola Kool','Keila vald','Harju maakond', 35);
INSERT INTO koolid VALUES('V?ru J?rve Kool','V?ru linn','V?ru maakond', 35);
INSERT INTO koolid VALUES('Klooga Kool','Keila vald','Harju maakond', 34);
INSERT INTO koolid VALUES('Libatse Lasteaed-Algkool','Halinga vald','P?rnu maakond', 34);
INSERT INTO koolid VALUES('Kajamaa Kool','Saku vald','Harju maakond', 33);
INSERT INTO koolid VALUES('Sadala P?hikool','Torma vald','J?geva maakond', 33);
INSERT INTO koolid VALUES('L?pe P?hikool','Koonga vald','P?rnu maakond', 32);
INSERT INTO koolid VALUES('Misso Kool','Misso vald','V?ru maakond', 32);
INSERT INTO koolid VALUES('Pikavere Lasteaed-Algkool','Raasiku vald','Harju maakond', 32);
INSERT INTO koolid VALUES('Harmi P?hikool','K?ue vald','Harju maakond', 31);
INSERT INTO koolid VALUES('Kaelase Kool','Halinga vald','P?rnu maakond', 30);
INSERT INTO koolid VALUES('Lindi Lasteaed-Algkool','Audru vald','P?rnu maakond', 30);
INSERT INTO koolid VALUES('Rakvere Vanalinna Kool','Rakvere linn','L??ne-Viru maakond', 30);
INSERT INTO koolid VALUES('Sonda Kool','Sonda vald','Ida-Viru maakond', 30);
INSERT INTO koolid VALUES('Tudu Lasteaed-P?hikool','Vinni vald','L??ne-Viru maakond', 30);
INSERT INTO koolid VALUES('Vajangu P?hikool','Tamsalu vald','L??ne-Viru maakond', 30);
INSERT INTO koolid VALUES('Tali P?hikool','Saarde vald','P?rnu maakond', 28);
INSERT INTO koolid VALUES('Mihkli Kool','Tapa vald','L??ne-Viru maakond', 27);
INSERT INTO koolid VALUES('Ritsu Lasteaed-Algkool','Helme vald','Valga maakond', 27);
INSERT INTO koolid VALUES('Luua Algkool','Palamuse vald','J?geva maakond', 26);
INSERT INTO koolid VALUES('Mehikoorma P?hikool','Meeksi vald','Tartu maakond', 26);
INSERT INTO koolid VALUES('Ruusa P?hikool','R?pina vald','P?lva maakond', 26);
INSERT INTO koolid VALUES('Tartu Rahvusvaheline Kool','Tartu linn','Tartu maakond', 26);
INSERT INTO koolid VALUES('Viira Kool','Tori vald','P?rnu maakond', 26);
INSERT INTO koolid VALUES('Kaagvere Erikool','M?ksa vald','Tartu maakond', 25);
INSERT INTO koolid VALUES('Pisisaare Algkool','Pajusi vald','J?geva maakond', 24);
INSERT INTO koolid VALUES('Valguta Lasteaed-Algkool','R?ngu vald','Tartu maakond', 24);
INSERT INTO koolid VALUES('Himmaste Algkool','P?lva vald','P?lva maakond', 23);
INSERT INTO koolid VALUES('Jaagu Lasteaed-P?hikool','P?rsti vald','Viljandi maakond', 23);
INSERT INTO koolid VALUES('Neeme Kool','J?el?htme vald','Harju maakond', 23);
INSERT INTO koolid VALUES('Aakre Lasteaed-Algkool','Puka vald','Valga maakond', 22);
INSERT INTO koolid VALUES('Hilariuse Kool','Tallinn linn','Harju maakond', 22);
INSERT INTO koolid VALUES('K?msi Lasteaed-Algkool','Hanila vald','L??ne maakond', 22);
INSERT INTO koolid VALUES('Salla P?hikool','Rakke vald','L??ne-Viru maakond', 22);
INSERT INTO koolid VALUES('Varbola Lasteaed-Algkool','M?rjamaa vald','Rapla maakond', 22);
INSERT INTO koolid VALUES('Vastseliina Internaatkool','Vastseliina vald','V?ru maakond', 22);
INSERT INTO koolid VALUES('Aruv?lja Lasteaed-Algkool','Audru vald','P?rnu maakond', 20);
INSERT INTO koolid VALUES('Kergu Lasteaed-Algkool','V?ndra vald','P?rnu maakond', 20);
INSERT INTO koolid VALUES('Kuremaa Lasteaed-Algkool','J?geva vald','J?geva maakond', 20);
INSERT INTO koolid VALUES('Pikakannu Kool','Lasva vald','V?ru maakond', 20);
INSERT INTO koolid VALUES('Salu Kool','Saue vald','Harju maakond', 20);
INSERT INTO koolid VALUES('T?ri Toimetulekukool','T?ri vald','J?rva maakond', 20);
INSERT INTO koolid VALUES('Ahula Lasteaed-Algkool','Albu vald','J?rva maakond', 18);
INSERT INTO koolid VALUES('Paide Valla Lasteaed-Kool','Paide vald','J?rva maakond', 18);
INSERT INTO koolid VALUES('Seljametsa Lasteaed-Algkool','Paikuse vald','P?rnu maakond', 18);
INSERT INTO koolid VALUES('Veltsi Lasteaed-Algkool','Rakvere vald','L??ne-Viru maakond', 18);
INSERT INTO koolid VALUES('?ru Lasteaed-Algkool','?ru vald','Valga maakond', 18);
INSERT INTO koolid VALUES('Kuimetsa Algkool','Kaiu vald','Rapla maakond', 17);
INSERT INTO koolid VALUES('Metsk?la Algkool','Lihula vald','L??ne maakond', 17);
INSERT INTO koolid VALUES('N?va Kool','N?va vald','L??ne maakond', 17);
INSERT INTO koolid VALUES('Puiatu Lasteaed-Kool','P?rsti vald','Viljandi maakond', 17);
INSERT INTO koolid VALUES('Rakvere Lille Kool','Rakvere linn','L??ne-Viru maakond', 17);
INSERT INTO koolid VALUES('Suigu Lasteaed-Algkool','Are vald','P?rnu maakond', 17);
INSERT INTO koolid VALUES('Suurem?isa Lasteaed-P?hikool','P?halepa vald','Hiiu maakond', 17);
INSERT INTO koolid VALUES('Vormsi Lasteaed-P?hikool','Vormsi vald','L??ne maakond', 17);
INSERT INTO koolid VALUES('Kabala Kool-Lasteaed','T?ri vald','J?rva maakond', 16);
INSERT INTO koolid VALUES('Kavastu Algkool-Lasteaed','Luunja vald','Tartu maakond', 16);
INSERT INTO koolid VALUES('Rakvere T?iskasvanute G?mnaasium','Rakvere linn','L??ne-Viru maakond', 16);
INSERT INTO koolid VALUES('Kasari P?hikool','Lihula vald','L??ne maakond', 15);
INSERT INTO koolid VALUES('K?pu Internaatkool','K?rgessaare vald','Hiiu maakond', 15);
INSERT INTO koolid VALUES('Pihtla Kool','Pihtla vald','Saare maakond', 15);
INSERT INTO koolid VALUES('Roosi Kool','P?lva linn','P?lva maakond', 15);
INSERT INTO koolid VALUES('K?rstna Kool','Tarvastu vald','Viljandi maakond', 14);
INSERT INTO koolid VALUES('Suislepa Lasteaed-Algkool','Tarvastu vald','Viljandi maakond', 14);
INSERT INTO koolid VALUES('Pikasilla Algkool','P?drala vald','Valga maakond', 13);
INSERT INTO koolid VALUES('Unipiha Algkool','Kambja vald','Tartu maakond', 13);
INSERT INTO koolid VALUES('Vahenurme Lasteaed-Algkool','Halinga vald','P?rnu maakond', 13);
INSERT INTO koolid VALUES('Ramsi Lasteaed-Kool','P?rsti vald','Viljandi maakond', 12);
INSERT INTO koolid VALUES('Vatla P?hikool','Hanila vald','L??ne maakond', 12);
INSERT INTO koolid VALUES('Vohnja Lasteaed-Algkool','Kadrina vald','L??ne-Viru maakond', 12);
INSERT INTO koolid VALUES('Prangli P?hikool','Viimsi vald','Harju maakond', 10);
INSERT INTO koolid VALUES('Aidu Lasteaed-Algkool','Pajusi vald','J?geva maakond', 9);
INSERT INTO koolid VALUES('Lahu Algkool','Rakke vald','L??ne-Viru maakond', 9);
INSERT INTO koolid VALUES('Lavassaare Lasteaed-Algkool','Lavassaare vald','P?rnu maakond', 9);
INSERT INTO koolid VALUES('Saduk?la Lasteaed-Algkool','Puurmani vald','J?geva maakond', 7);
INSERT INTO koolid VALUES('Ruhnu P?hikool','Ruhnu vald','Saare maakond', 6);
INSERT INTO koolid VALUES('Massiaru Algkool','H??demeeste vald','P?rnu maakond', 3);
ALTER TABLE koolid ADD id INT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;